version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 3000:3000
  postgres:
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
        - postgres
    env_file:
      - .env
    ports:
        - 15432:80
